config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  resources :books

  namespace :api do
    namespace :v1 do
      resources :books
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    validates :name, presence: true, allow_blank: false

    has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author

  validates :title, presence: true, allow_blank: false
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, :email, presence: true, allow_blank: false
  validates :email, email: true
end

app/controllers/api/v1/books_controller.rb
class Api::V1::BooksController < ApplicationController
    def index
        @books = Book.paginate(page: params[:page], per_page: params[:per_page].blank? ? 10 : params[:per_page])
        render json: {
            data: @books,
            status: :success,
            code: 200,
            message: "Book data retrieved successfully",
            metadata: {
                page: params[:page].blank? ? 1 : params[:page].to_i,
                count: @books.total_entries,
                total_page: @books.total_pages
            }
        }
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!
    before_action :find_book, only: :show

    def index
        @books = Book.paginate(page: params[:page], per_page: 10)
    end

    def show
    end

    def new
        @book = Book.new
        @authors = Author.all.map { |author| [author.name, author.id] }
    end

    def create
        @book = Book.create(book_params.merge(created_by: current_user.id))

        if @book.save
            SendEmailJob.perform_async(@book.id, current_user.id)
            redirect_to books_path, notice: "Book has been created"
        else
            render :new
        end
    end

    private

    def find_book
        @book = Book.find_by_id(params[:id])

        if @book.blank?
            redirect_to books_path, alert: "Books not found"
        end
    end

    def book_params
        params.require(:book).permit(:title, :author_id, :published_year)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/api/v1/books_helper.rb
module Api::V1::BooksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/index.html.erb
<h1>Books</h1>

<table>
    <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Published Year</th>
        <th>Action</th>
    </tr>
    <% @books.each do |book| %>
        <tr>
            <td><%= book.title %></td>
            <td><%= book.author.name %></td>
            <td><%= book.published_year %></td>
            <td>
                <%= link_to "View", book_path(book) %>
            </td>
        </tr>
    <% end %>
</table>

<%= will_paginate @books %>

<%= link_to "Back", root_path %>
<%= link_to "New", new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= form_for @book do |f| %>
    <table>
        <tr>
            <td>Title</td>
            <td><%= f.text_field :title, required: true %></td>
        </tr>
        <tr>
            <td>Author</td>
            <td><%= f.select :author_id, @authors, {}, { required: true, selected: @book.author_id } %></td>
        </tr>
        <tr>
            <td>Published Year</td>
            <td><%= f.select :published_year, (Date.today.year-100)..(Date.today.year), :selected => Time.current.year %></td>
        </tr>
        <tr>
            <td colspan="2"><%= f.submit %></td>
        </tr>
    </table>
<% end %>

app/views/books/show.html.erb
<h1>Detail Book</h1>

<table>
    <tr>
        <th>Title</th>
        <td><%= @book.title %></td>
    </tr>
    <tr>
        <th>Author</th>
        <td><%= @book.author.name %></td>
    </tr>
    <tr>
        <th>Published Year</th>
        <td><%= @book.published_year %></td>
    </tr>
</table>

<%= link_to "Back", books_path %>

app/views/home/index.html.erb
<ul>
    <li><%= link_to "Books", books_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorTechnicalTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>